# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KAk/ubeZSlK5JytI6ETX+Is5fLsgVZJlsvHpraCBkD18LCucJpqZndQJ/HypL5sgwSyp7JZq1boc3XJLGBtZTZ/o5kAcSh75JtHqUfhu7puTyRnYhGwtLTiNJLgoBqyN749u+KpCgYN4MNkgPaYTb4FW1xLW7JoZW7ebrKhm7epIYzThLXb9ZcIUBLoXlreza/zQ0eYbH+tfv8uNPiE5L4Jaq5aOVaZPf2QCNvQzuLgTGFFTK+GYocQH4MttJg+MKe8XMMwSmA8CZDI+SIjgmrXFgSOX3XT+/Sbe9pdMnWuRjD+I8cHvjh0xiFeaGu97JRMmnoM2Gc/ZAtQB2QxlYKK5c0bgsCDyq9Reji2p06y+RE+s5WuabdYXcwKsMsMCVBZ4OxtVYI7Oi/CslpeMnHy3iwidLDJbzf2DMN39OTI8xUWczQQanC21ajRN8MCXQDxvS+4xoYQfDjzYc2Zrl9u2qdIo5FcJvJxv5dIjyWaIE5+kgoPEvf+GXIt85Ok3P5uZVjckx3CjsQvwwvNFIvuMxJAwA2usuBgPqr/dbZPwuAnA2Csdv80wx1zDDT2Ai09bqf95PhwvWMhNTaR608v8lv4FXV8VvkHNjXL0dj8hpBbb37txEZwZac0TMQsLHRT4tM3bPXT8Hr5aSavszDZ1g8sMAsjgKnEsBbYVI4I="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
