travis:
  secure:
    BINSTAR_TOKEN: fh21FP+zVn3UHsppnWFb+eHuR+qzvEX/IPXxAfrnL/kRccY2bUmUH88JtBsjdalcQMBsKewg/8LablhtqhszFTdtaiGNXvggtFT/KO8mJpLdKvDlBcoeEVQZIk6AyGfz1cFGnCP6n09RRxj5qvoQjGEB63dS6YAz0iMRHnjMCShUJYwAJhcG3G1RQaWZFEe1C03RaxBYF+Xr7iBn2PTjTIv9IfhIcF0kRid2N4BrfELaBL++dx2GDY7F3WR1jcb0CvMkrYMTdzv3TxNzKAxpCReAEqJHKL/BKpMhPckNkqroCyMhvr5lVa0umPo5b4Qhndrtw1v0hueTosAyrkW3dcmr9p2KxZu4BpNpOyPU3YdX19lfI97JaIyN6edhYrlSNtl0Uh2cr2M1GclmAAliZGCzaPn4DA/rGmocLWZwnbb98eGEU+Imt7ExC254CW1DtL7m+MYdwuUxNdkliET8qRkoO3aur1bPACUm13ex/g59/cK6/ocUaZlc8ly2gnIUOOdPDryq9GY83TW2njueQ8sLYGEKWaF9RDbiS3CE3Dh5Jt+bVq1vqLhhzFRe4n2UFo07fo6Xy8vP1UtvikxuM0D/XwmgLlx52LGqDDdlrdmuYXr8HzYtejq8DwFsSwAC5t0oYl1aAOS2x2MYn8j7br0fpajQYetTCBc6sPDDP7Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
