travis:
  secure:
    BINSTAR_TOKEN: IQ3lOzqEhYFMbbpSK7+iNsR1yUcAPaFXmfRRxRoPAFPFmHIbRZTYBUIZ3pI+NiHmkFt847rfaT8/go2lljO5Tc0EIpfn2COOG9G+pQ1sG+YFgkmrfWmuzlWmFO2LQKUqVH+UJNdsQMd6e3cimyw0w/c2aPRGmPw+6P9aGXoG8xKJfsEm8oj5yjsCAYe8kAyMyrdRsBStJ/k0kBz0rkhXxo8bgFX/9iQCzMgFL0lMyin/XQ4BPvqPfwOxtGZ+nYh0JHxNiIMb+aC5uH/gy/USVGG3RJpt8fKRa2Gg8/9uOoN/2dnTWgpkXgBSy2/lKRcbv213hia2iz09DC5tgYTCUuxEQPQxa54o/SqDrdfa6bPxcAtP8pr8pTyYYUJwepcCD3uZjgsZJ9IT7n61DaKFp1Ysx+o0JLamp5ZudnA+MRe3u/gslzvX2HpFbKUaPWXCpFVfIb0zzLJfK4dB3L5pPhmJTteRBI5vgS/hE1G0NFzDPEN9WYKKYEf5Tj8XFg+LbEG/vLK8egt5LXCf1h6nU9uINl8P/biNjB1KEvpdfviyvz5VDdgGxunfOBKqRzZzjFlUKirArdSVG29pCu2+F0amErMZLoKjS86szyYZMZsGl1wieMJAyQpxbtTKD3VAt5x9lS1ctszRELo54IBqnU5C/46bcjiTR7uJ2uMA1xw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
