travis:
  secure:
    BINSTAR_TOKEN: ETkE6HHh76Ekjam0zNz6adz67Esfai7+PJ5hs6z55M+GgimM7aaLM7cKDQktXEE7krTtp0cQbRLJm3F0/v5Lp0kMeTb5KAe93lkN1+uD3f36fBgbkL1/cqtzZBQ9Ab4HaRmyfSboLonXyZyiFRIaa7oIwPO9tki5K7TXp1d16yt3bAjBNpGyPI/j4eCQGTsnUR6bDvo8zs6LUR6aIELKM2ig4F1/u1pSKW/4tASKySDqumUtYWCGL6J40AXi2AKbPWTbQGPGpbRgRcx7XKIf8iKPv6mPgVny1KWyLEH2ad7ukqzTsz5nMRtYpqSaPWDCvClGMV6z83WjmAzrsAluS1EP2z+OXnuDDDFvOsNoztKwUYdeRNeEk1kexV3OCdEljLsjTGaBZCWAgww3o/HJsyiJq/cNB524OhpZcZfPW/ns0H2/A6eZTaMqyUc83ISBcO27Gj0QC6jRvhs1qU5PbtTAgTZ5cKi7GFxnXOstsdWhWjEtW2RDu13Ww8F9m377kcGS9ELErDhZdI9lGm0FGKQcl9io8gKmEcb5P1iG8jNxUtDln4uDRkUkiTKVL2ZpQqC8mP1RzU39Q595c8hldGORSkHyc4PXFd2RYLveUDH7U/weuMzLY7aSNoC9nAIj5gpY4zj3WzH1kdG/f7bMexojR67CMEVAuV4p7uP2WkE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
