travis:
  secure:
    BINSTAR_TOKEN: lXThBYulvbY5MFaCedB80jl4a715czOoCfceuBjdVrQ3O8Cvn2X7EjB6O3oCRFBTMA/cu/JadWc5QBMXLsQ0hgWeSi08wCbtV0EEgOse8+OsQ0haWt+R25ITpoV+PKh9N+ZV71QNsjt+G25mElLXEFR1C4cnwzA0OWCAc6dcu0ZYuJKtzaFgHrMZPdglGv66X4CsIr8omlXkjwpIdkrjoNl16QdB2Ju55WD3PTyDflVKyxIp2F8Lm0RXNqbqP026N/cm868HwasDKJZwVsmtHJt1vHhtipt4EZ+rzze58GeFZafsS6Be8p4fH3IWBt+Q5aT+ijkJVvWgfil6Gx1YaA7zcvGHCMEv+ggreOrR4xPF4GBJIKGk+tJWzfCv6qprheIBAiWwJqfEy07Fq4HA4Jhslgf8yXHwZ1gL7GIOeSIb18e8xuRL66dN+fob1Fw6RNSlGPS9Nlzn+Jc7iN4udkx0MG3altgRdNs8cZCX2cA7V9fgS5QXHye8E1kpLSIQ2/LiAc0nov0uJcf1PDz0MHHd9YPv6a4FRB+HLKmZs7EsFWiAdRVYP4FP9rgR/jjW6uPI9y6eiO0FZPEYjUrwhBNwXZdnLpKPm7dKWKiXELGqOhrkf8ig55D4Psja2toQkPXwT9MAHqNxnsVKD3urf5+5cxb8rIjY2cqWsSN0ogY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
